### ISSUE TITLE
Quote reporting

### ISSUE THREAD

**Issue by SebastianBilek** [ArchieHickmott/quotebook#15]
Reports might contain a description and severity. Reasons might include: duplicates, innappropriate, personal reasons, etc...
Admins should have a reports console where they can accept/deny the report.

**Comment by ArchieHickmott** [comment]
created reports table in restructured database
table is created as such:
```sql
CREATE TABLE "" (
    reportid                PRIMARY KEY,
    reporter                REFERENCES users (userid),
    quote                   REFERENCES quotes (quoteid),
    reason   TEXT,
    details  TEXT,
    status   INTEGER (0, 2) DEFAULT (0) 
);

```
the idea is that:
reason is the duplicates, innappropriate, personal reasons, etc...
details is a description made by the reporter on why it should be removed
status is either 0 or 1 or 2 where it's 0 if an admin hasn't looked at it yet, 1 if they've started looking at it and 2 if it's close

**Comment by Helios-fr** [comment]
Auto-Moderation could be implemented, where if a quote is reported by different users multiple times, it should be flagged and hidden from view until verified by administrator.

Also potentially using code to check the similarity of a quote to other existing quotes to prevent duplicates and repeated spam.

**Comment by ArchieHickmott** [comment]
I'll think about auto-mod later
