### ISSUE TITLE
Weird server crashing bug

### ISSUE THREAD

**Issue by ArchieHickmott** [ArchieHickmott/quotebook#18]
There is a weird bug somewhere in the code that stops the server from responding to any requests.
No information on how this is caused is known as of the moment

**Comment by Helios-fr** [comment]
Could this error be caused by the loop on the main page on line 183 of `app.py` specifically this code:
```py
while True:
    id = randint(1, num)
    try:
        quote = db.query(f"SELECT name, year, quote FROM quotes WHERE rowid = {id}")[0]
    except IndexError:
        pass
    else:
        break
```

**Comment by ArchieHickmott** [comment]
2am ah code. It's definitely this
